[database]
host = "127.0.0.1"
port = 5433
username = "smuggr"
database = "smuggr"

[bridge]
broker_host = "tcp://localhost"
broker_port = "1883"
mdns_service_instance_name = "SmuggrNetworkMQTTBroker"
mdns_domain = ""
mdns_host_name = ""
client_id = "smuggr_network"
keep_alive_seconds = 10
disconnect_miliseconds = 250
plugins_directory = "build/plugins"

[api]
port = 8000
jwt_lifespan_minutes = 1440
trusted_cors = [
	"http://localhost:3000",
	"http://localhost:8000"
]